version : '3'

services:
    client:
        image: client
        build:
          context: client
          dockerfile: Dockerfile
        ports:
            - "5500:80"
    lb:
        image: haproxy:2.2
        ports:
            - "8282:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    ws1:
        image: wsapp
        build:
          context: backend
          dockerfile: Dockerfile
        environment:
            - REDIS_HOST=rds
    ws2:
        image: wsapp
        build:
          context: backend
          dockerfile: Dockerfile
        environment:
            - REDIS_HOST=rds
    ws3:
        image: wsapp
        build:
          context: backend
          dockerfile: Dockerfile
        environment:
            - REDIS_HOST=rds
    ws4:
        image: wsapp
        build:
          context: backend
          dockerfile: Dockerfile
        environment:
            - REDIS_HOST=rds
    rds:
        image: redis